### PR TITLE
Remove _base_manager attribute for Django 1.10 support

### PR DESCRIPTION
**Pull request by codingjoe**
I based this on my tox commit to see if CI passes.

### CODE REVIEW

**Comment by scott-w** [comment]
Hi @codingjoe, thanks for the work on this!

Is this intended to close #20 simultaneously?

**Comment by codingjoe** [comment]
@scott-w yes, more or less. You can merge #20 and I rebase this one, or you merge both at once. I just needed to show, that it works on all Django versions, hence me reusing this commit.

**Comment by codingjoe** [comment]
@scott-w would you mind issuing a new PyPi release?

**Comment by scott-w** [comment]
Yeah I'll get that done today

**Pull request merged**
