### PR TITLE
Adds support for multicolumn indexes in materialized views.

### PR DESCRIPTION
**Pull request by peterburlakov**

### CODE REVIEW

**Comment by peterburlakov** [comment]
Hi, @scott-w 
CircleCI is a bit unstable today ;) build failed coz of their internal problems... can you restart it?

**Comment by scott-w** [comment]
Classic CircleCI. I've set it to rebuild 👍

**Comment by scott-w** [comment]
Seems to still be failing. I'll open a support ticket with CircleCI and keep you updated :)

**Comment by scott-w** [comment]
I've merged in #35 that includes this PR 👍 

Thanks @peterburlakov!

**Pull request closed without merging**
