### PR TITLE
Adds a way around multi-tenant applications

### PR DESCRIPTION
**Pull request by kingbuzzman**
Fixes issue https://github.com/mypebble/django-pgviews/issues/50

### CODE REVIEW

**Comment by kingbuzzman** [comment]
Whats going on with circleci? Why are the tests not running?

**Comment by kingbuzzman** [comment]
https://github.com/mypebble/django-pgviews/pull/49 Whoops. Seems like i recreated your PR

**Review by Mogost — APPROVED** [review]

**Comment by kingbuzzman** [comment]
@mypebble is this project still maintained?

**Comment by scott-w** [comment]
Hey, @tpict and I don’t work at Pebble any more, so I’m not sure if anyone is looking at this repo.

I might be a little while but let me see if I can still do Admin on this project when I can get to a PC.

**Comment by kingbuzzman** [comment]
@scott-w any update?

**Comment by scott-w** [comment]
Hey @kingbuzzman, it seems I don't have any rights to this project any more. It looks like Tom is still listed but I can't get in contact with him any more :(

**Comment by kingbuzzman** [comment]
So.. is it dead? should i go else where?

**Comment by scott-w** [comment]
I just managed to get in touch with Tom and I’m going to see if he can give me write access to the repo.

Neither of us will be able to update PyPI though, so it might need a new package to achieve that. Long term, I doubt either of us will be particularly active in the project as Tom is extremely busy in his new job and I don’t work with Django my more.

**Comment by kingbuzzman** [comment]
Makes sense. Thank you for your efforts. I'll move this code elsewhere, maybe over to https://github.com/SectorLabs/django-postgres-extra

I'll try to port this code over for issue: https://github.com/SectorLabs/django-postgres-extra/issues/5

**Comment by Mogost** [comment]
@kingbuzzman Good idea with joining with `django-postgres-extra`!
My project that uses `django-pgviews` is already a dependent on `django-postgres-extra` (I think that many have the same situation).
If `django-postgres-extra` refuses to accept us, we can consider the possibility of migration under the wing of [JazzBand](https://github.com/jazzband/)

**Pull request closed without merging**
