### PR TITLE
Switched to using Six

### PR DESCRIPTION
**Pull request by MightySCollins**
As described in #53 this project does not work with Django 3

### CODE REVIEW

**Comment by Mogost** [comment]
requires section in `setup,py` need to be fixed

**Comment by MightySCollins** [comment]
Well it actually need to be done properly I just raised it so people could quickly see. In some ways I might revert the `six.string_types` -> `str` change and make it use six directly just to make it less breaking

**Comment by robvdl** [comment]
@MightySCollins there is another PR "Add Django 2.2 support" that does this #56 

This seems important to focus on getting through as 2.2 is the current LTS with 1.11 approaching EOL

**Comment by scott-w** [comment]
Thanks for the PR. I'm going to close this in favour of #56.

**Pull request closed without merging**
